esphome:
  name: picocalc
  friendly_name: PicoCalc
  libraries:
    - "adafruit/Adafruit GFX Library"
    # - "Adafruit_ILI9341"

rp2040:
  board: rpipico2w
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git#develop
    version: dev

picocalc:
  id: clockwork


####### Rendering Engine #######
# Pick one and uncomment it:
# 
# The hello-world lvgl example from home assistant.
#``` 
# lvgl:
#```
#
# OR:
# My standalone lvgl example that includes sensors and a clock
#   Based largely on the esphome lvgl cookbook: https://esphome.io/cookbook/lvgl#theme-and-style-definitions
#```
# <<: !include includes/lvgl/lvgl.yaml
#```
#
# OR:
# The Adafruit GFX library example.
#   Based largely on the adafruit_gfx example: https://github.com/adafruit/Adafruit-GFX-Library/blob/master/examples/mock_ili9341/mock_ili9341.ino
#``` 
# adafruit_gfx:
#```
#
# OR:
# The CTX Graphics Library.
#   Using the: https://ctx.graphics/ library
#``` 
ctx_gfx:
#```
##### ^ Rendering Engine ^ ######


<<: !include component/picocalc/picocalc.yaml

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret pico_api_key

ota:
  - platform: esphome
    password: !secret pico_ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret mobile_wifi_ssid
      password: !secret mobile_wifi_password
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "PicoCalc Fallback Hotspot"
    password: !secret pico_wifi_ap_password
